name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        # Assuming you have tests defined for your FastAPI endpoints
        pytest tests/

  dockerize-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    env:
      IMAGE_NAME: your-dockerhub-username/fastapi-app  # Replace with your Docker Hub username
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Push Docker image to Docker Hub
      run: docker push $IMAGE_NAME:latest

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull $IMAGE_NAME:latest
          docker stop fastapi-app || true
          docker rm fastapi-app || true
          docker run -d -p 80:80 --name fastapi-app $IMAGE_NAME:latest
